name = "low_alt"
description = "Low altitude flight - terrain warning"

[state]
valid = true
"aileron, %" = 0.0
"elevator, %" = -2.0
"rudder, %" = 0.0
"flaps, %" = 0.0
"gear, %" = 0.0
"airbrake, %" = 0.0
"H, m" = 50.0
"TAS, km/h" = 300.0
"IAS, km/h" = 280.0
"M" = 0.25
"AoA, deg" = 2.5
"AoS, deg" = 0.0
"Ny" = 1.0
"Vy, m/s" = -2.0
"Wx, deg/s" = 0.0
"Mfuel, kg" = 4000.0
"Mfuel0, kg" = 7460.0
"Mfuel 1, kg" = 500.0
"throttle 1, %" = 60.0
"power 1, hp" = 5000.0
"RPM 1" = 4500.0
"manifold pressure 1, atm" = 0.9
"oil temp 1, C" = 70.0
"thrust 1, kgs" = 1200.0
"efficiency 1, %" = 80.0
"throttle 2, %" = 60.0
"power 2, hp" = 5000.0
"RPM 2" = 4500.0
"manifold pressure 2, atm" = 0.9
"oil temp 2, C" = 70.0
"thrust 2, kgs" = 1200.0
"efficiency 2, %" = 80.0

[indicators]
valid = true
army = "air"
type = "fa_18c_switzerland"
speed = 0.8
pedals1 = 0.0
pedals2 = 0.0
pedals3 = 0.0
pedals4 = 0.0
pedals5 = 0.0
stick_elevator = -0.1
stick_ailerons = 0.0
vario = -2.0
altitude_hour = 50.736572
altitude_min = 50.736572
altitude_10k = 50.736572
altitude1_10k = 50.736572
radio_altitude = 48.0
aviahorizon_roll = 0.0
aviahorizon_pitch = -1.0
bank = 0.0
turn = 0.0
compass = 90.270599
clock_hour = 0.0
clock_min = 45.0
clock_sec = 30.0
airbrake_lever = 0.0
gears = 0.0
gear_lamp_down = 0.0
gear_lamp_up = 1.0
gear_lamp_off = 1.0
throttle = 0.6
throttle1 = 0.6
weapon2 = 0.0
weapon3 = 0.0
flaps_indicator = 0.0
flaps_indicator1 = 0.0
aoa_indexer1 = -0.1
aoa_indexer2 = -0.1
aoa_indexer3 = -0.1
blister1 = 1.0
blister2 = 1.0
blister3 = 1.0
blister4 = 1.0
blister5 = 1.0
blister6 = 1.0
blister7 = 1.0
blister8 = 1.0
blister9 = 1.0
blister10 = 1.0
blister11 = 1.0

[map_info]
grid_size = [131144.093750, 131144.093750]
grid_steps = [16393.011718750, 16393.011718750]
grid_zero = [-65572.0468750, 65572.0468750]
hud_type = 0
map_generation = 2
map_max = [65536.0, 65536.0]
map_min = [-65536.0, -65536.0]
valid = true

[[map_objects]]
type = "aircraft"
color = "#faC81E"
"color[]" = [250, 200, 30]
blink = 0
icon = "Player"
icon_bg = "none"
x = 0.5
y = 0.5
dx = 1.0
dy = 0.0

[[map_objects]]
type = "airfield"
color = "#174DFF"
"color[]" = [23, 77, 255]
blink = 0
icon = "none"
icon_bg = "none"
sx = 0.6
sy = 0.5
ex = 0.62
ey = 0.48
